# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GlovoChallenge' do
  
  inhibit_all_warnings!
  use_frameworks!

  # Pods for GlovoChallenge
  pod 'GoogleMaps'
  pod 'SnapKit', '~> 4.0.0'
  pod 'Alamofire'
  pod 'ReactiveKit'
  pod 'Bond'

end
